/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Condition = IDL.Variant({
  'new' : IDL.Null,
  'good' : IDL.Null,
  'poor' : IDL.Null,
  'average' : IDL.Null,
  'excellent' : IDL.Null,
});
export const Submission = IDL.Record({
  'age' : IDL.Nat,
  'customerName' : IDL.Text,
  'model' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'brand' : IDL.Text,
  'phone' : IDL.Text,
  'condition' : Condition,
});
export const SubmissionResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllCustomerContacts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text, IDL.Text))],
      [],
    ),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], []),
  'getSubmission' : IDL.Func([IDL.Text], [IDL.Opt(Submission)], []),
  'submitAC' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Condition, IDL.Text, IDL.Text, IDL.Text],
      [SubmissionResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Condition = IDL.Variant({
    'new' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
    'average' : IDL.Null,
    'excellent' : IDL.Null,
  });
  const Submission = IDL.Record({
    'age' : IDL.Nat,
    'customerName' : IDL.Text,
    'model' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'brand' : IDL.Text,
    'phone' : IDL.Text,
    'condition' : Condition,
  });
  const SubmissionResult = IDL.Variant({
    'error' : IDL.Text,
    'success' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllCustomerContacts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text, IDL.Text))],
        [],
      ),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], []),
    'getSubmission' : IDL.Func([IDL.Text], [IDL.Opt(Submission)], []),
    'submitAC' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Condition, IDL.Text, IDL.Text, IDL.Text],
        [SubmissionResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };