/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type SubmissionResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: string;
};
export interface Submission {
    age: bigint;
    customerName: string;
    model: string;
    email: string;
    timestamp: Time;
    brand: string;
    phone: string;
    condition: Condition;
}
export type Time = bigint;
export enum Condition {
    new_ = "new",
    good = "good",
    poor = "poor",
    average = "average",
    excellent = "excellent"
}
export interface backendInterface {
    getAllCustomerContacts(): Promise<Array<[string, string, string, string]>>;
    getAllSubmissions(): Promise<Array<Submission>>;
    getSubmission(id: string): Promise<Submission | null>;
    submitAC(brand: string, model: string, age: bigint, condition: Condition, customerName: string, phone: string, email: string): Promise<SubmissionResult>;
}
import type { Condition as _Condition, Submission as _Submission, SubmissionResult as _SubmissionResult, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllCustomerContacts(): Promise<Array<[string, string, string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomerContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomerContacts();
            return result;
        }
    }
    async getAllSubmissions(): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmission(arg0: string): Promise<Submission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmission(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmission(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAC(arg0: string, arg1: string, arg2: bigint, arg3: Condition, arg4: string, arg5: string, arg6: string): Promise<SubmissionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAC(arg0, arg1, arg2, to_candid_Condition_n7(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return from_candid_SubmissionResult_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAC(arg0, arg1, arg2, to_candid_Condition_n7(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return from_candid_SubmissionResult_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Condition_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Condition): Condition {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionResult): SubmissionResult {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Submission_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Submission): Submission {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Submission]): Submission | null {
    return value.length === 0 ? null : from_candid_Submission_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    customerName: string;
    model: string;
    email: string;
    timestamp: _Time;
    brand: string;
    phone: string;
    condition: _Condition;
}): {
    age: bigint;
    customerName: string;
    model: string;
    email: string;
    timestamp: Time;
    brand: string;
    phone: string;
    condition: Condition;
} {
    return {
        age: value.age,
        customerName: value.customerName,
        model: value.model,
        email: value.email,
        timestamp: value.timestamp,
        brand: value.brand,
        phone: value.phone,
        condition: from_candid_Condition_n4(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: string;
}): {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: string;
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    good: null;
} | {
    poor: null;
} | {
    average: null;
} | {
    excellent: null;
}): Condition {
    return "new" in value ? Condition.new : "good" in value ? Condition.good : "poor" in value ? Condition.poor : "average" in value ? Condition.average : "excellent" in value ? Condition.excellent : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Submission>): Array<Submission> {
    return value.map((x)=>from_candid_Submission_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Condition_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Condition): _Condition {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Condition): {
    new: null;
} | {
    good: null;
} | {
    poor: null;
} | {
    average: null;
} | {
    excellent: null;
} {
    return value == Condition.new ? {
        new_: null
    } : value == Condition.good ? {
        good: null
    } : value == Condition.poor ? {
        poor: null
    } : value == Condition.average ? {
        average: null
    } : value == Condition.excellent ? {
        excellent: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
